INSERT INTO categoria (nome) VALUES ('Pizza');
INSERT INTO categoria (nome) VALUES ('Bebida alcoólica');
INSERT INTO categoria (nome) VALUES ('Bebida não alcoólica');

INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('Calabresa', '30.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZCLB.jpg', 'Mussarela, calabresa e cebola, oregano.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('Mussarela', '30.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZMUS.jpg', 'Queijo mussarela e oregano.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('Pepperoni', '30.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZPEP.jpg', 'Mussarela, oregano e pepperoni.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('Bauru', '30.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZBU.jpg', 'Mussarela, presunto, requeijão, oregano e tomate.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('3 Queijos', '35.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZQU.jpg', 'Mussarela, requeijão, oregano e parmesão ralado.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('Frango com requeijão', '35.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZFR.jpg', 'Frango desfiado, cebola, oregano e requeijão.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('Portuguesa', '35.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZPT.jpg', 'Mussarela, presunto, ovo de codorna, azeitona preta, cebola, oregano e pimentão verde.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('Toscana', '35.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZTOS.jpg', 'Mussarela, calabresa, requeijão, azeitona preta, cebola, tomate, oregano e manjericão.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('Calabresa Especial', '35.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZECAL.jpg', 'Mussarela, azeitona preta, calabresa, cebola, oregano e Cream Cheese.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('Corn & Bacon', '40.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZCRBK.jpg', 'Mussarela, bacon, oregano e milho.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('4 Queijos', '40.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZFQ.jpg', 'Mussarela, requeijão, gorgonzola, oregano e parmesão ralado.' , 1);
INSERT INTO produto (nome, preco, imagem, descricao, id_categoria) VALUES ('Egg & Bacon', '40.0', 'https://cache.dominos.com/olo/6_62_4/assets/build/market/BR/_pt/images/img/products/larges/S_PIZEGK.jpg', 'Mussarela, bacon, cebola, cream cheese, oregano e ovo de codorna.' , 1);